[package]
name = "polars-finance"
version = "0.1.0"
edition = "2021"

[lib]
name = "polars_finance"
crate-type= ["cdylib"]

[dependencies]
pyo3 = { version = "*", features = ["extension-module", "abi3-py38"] }
pyo3-polars = { version = "*", features = ["derive", "lazy"] }
serde = { version = "1", features = ["derive"] }
polars = { version = "*", features=["diff", "lazy", "performant", "polars-ops", "dtype-date", "dtype-datetime", "dtype-struct"]}

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }
