[build-system]
requires = ["maturin>=1.1,<2.0", "polars>=0.20.6"]
build-backend = "maturin"

[project]
name = "polars-finance"
requires-python = ">=3.8"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
version="0.1.0"

dependencies = [
    "polars>=0.20.13",
]
license = { file = "LICENSE" }
readme = "README.md"

[tool.maturin]
features = ["pyo3/extension-module"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff]
lint.select = [
  "ALL",
]
lint.ignore = [
  'A003',
  'ANN101',
  'ANN401',
  'ARG002',  # todo: enable
  'ARG003',  # todo: enable
  'C901',
  'COM812',
  'D100',
  'D103',
  'D104',
  'D105',
  'D107',
  'D203',
  'D212',
  'DTZ',
  'E501',
  'FBT003',  # todo: enable
  'FIX',
  'ISC001',
  'PD',
  'PLR0911',
  'PLR0912',
  'PLR5501',
  'PLR2004',
  'PT011',
  'PTH',
  'RET505',
  'S',
  'SLF001',
  'TD',
  'TRY004'
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]